export enum ShiftEnum{
    GENERAL='GENERAL',
    A='A',
    B='B',
    C='C',
    D='D'
}

export enum WorkstationEnum{
    TOOLING_STATION='TOOLING_STATION',
    HYDRAULIC_POWER_UNIT='HYDRAULIC_POWER_UNIT',
    HYDRAULIC_PRESS_1='HYDRAULIC_PRESS_1',
    HYDRAULIC_PRESS_2='HYDRAULIC_PRESS_2'
}

export enum MaintenanceTask{
    TOOLING_INSPECTION_AND_MAINTENANCE='TOOLING_INSPECTION_AND_MAINTENANCE',
    OILING='OILING',
    PRE_SHIFT_INSPECTION='PRE_SHIFT_INSPECTION',
    PRESS_MAINTENANCE='PRESS_MAINTENANCE',
    HYDRAULIC_SYSTEM_MAINTENANCE='HYDRAULIC_SYSTEM_MAINTENANCE',
    COOLING_SYSTEM_MAINTENANCE='COOLING_SYSTEM_MAINTENANCE',
    SAFETY_SYSTEM_CHECKS='SAFETY_SYSTEM_CHECKS',
    CALIBRATION_AND_ADJUSTMENTS='CALIBRATION_AND_ADJUSTMENTS',
    HOUSEKEEPING_AND_CLEANLINESS='HOUSEKEEPING_AND_CLEANLINESS',
    DOCUEMNTATION_AND_RECORD_KEEPING='DOCUEMNTATION_AND_RECORD_KEEPING'
    

}


