export enum SupplyChainIssueCategoryEnum {
    PACKAGING_SPECIFICATION='PACKAGING_SPECIFICATION',
    LABELLING_SPECIFICATION='LABELLING_SPECIFICATION',
    DELIVERY_DOCUMENT_SPECIFICATION='DELIVERY_DOCUMENT_SPECIFICATION',
    LOADING_SPECIFICATION='LOADING_SPECIFICATION',

}

export enum SupplyChainIssueDescriptionEnum{
    PACAKGING_DESIGN_COMPLIANCE_FAILURE=' PACAKGING_DESIGN_COMPLIANCE_FAILURE',
    QUANTITY_COMPLIANCE_FAILURE='QUANTITY_COMPLIANCE_FAILURE',
    DAMAGED_OR_DIRTY_PACKAGING='DAMAGED_OR_DIRTY_PACKAGING',
    POOR_READBILITY='POOR_READBILITY',
    MISLABELLING='MISLABELLING',
    LABEL_DATA_MISSING='LABEL_DATA_MISSING',
    INACURATE_DELIVERY_DOCUMENT_DATA='INACURATE_DELIVERY_DOCUMENT_DATA',
    LOADING_SPECS_NON_CONFIRMITY='LOADING_SPECS_NON_CONFIRMITY',
    SAFETY_PRECAUTION_NON_CONFIRMITY='SAFETY_PRECAUTION_NON_CONFIRMITY',

}

export enum SupplyChainSubIssueEnum{
    INCORRECT_PACKAGING='INCORRECT_PACKAGING',
    UNAUTHORIZED_ALTERNATIVE_PACKAGING='UNAUTHORIZED_ALTERNATIVE_PACKAGING',
    INCORRECT_PALLETIZATION='INCORRECT_PALLETIZATION',
    PACKAGING_QUANTITY_NON_CONFIRMITY='PACKAGING_QUANTITY_NON_CONFIRMITY',
    WEIGHT_UNDER_OVER_TOLERANCE='WEIGHT_UNDER_OVER_TOLERANCE',
    DIRTY_PACKAGING='DIRTY_PACKAGING',
    DAMAGED_PACKAGING='DAMAGED_PACKAGING',
    UNSAFE_PACKAGING='UNSAFE_PACKAGING',
    NON_SCANNABLE_BARCODE='NON_SCANNABLE_BARCODE',
    DAMAGED_LABEL='DAMAGED_LABEL',
    INCORRECT_QUANTITY_INDICATION='INCORRECT_QUANTITY_INDICATION',
    NON_COMPLIANCE_CUSTOMER_TRANSPORT_STANDARD='NON_COMPLIANCE_CUSTOMER_TRANSPORT_STANDARD',
    DISPATCH_ORDER_MISSING='DISPATCH_ORDER_MISSING',
    MATERIAL_NUMBER_MISSING='MATERIAL_NUMBER_MISSING',
    INVOICE_NUMBER_MISSING='INVOICE_NUMBER_MISSING',
    TEST_CERTIFICATE_MISSING='TEST_CERTIFICATE_MISSING',
    RACK_OR_PALLET_CANT_BE_UNLOADED='RACK_OR_PALLET_CANT_BE_UNLOADED',
    RACK_OR_PALLET_INCORRECTLY_LOCATED='RACK_OR_PALLET_INCORRECTLY_LOCATED',
    HAZARDOUS_LOADING='HAZARDOUS_LOADING',
    NON_COMPLIANCE_WITH_INTERNAL_TRAFFIC_RULE='NON_COMPLIANCE_WITH_INTERNAL_TRAFFIC_RULE'


}

